@extends('layouts.public')
@section('title', 'Parke’o · Reserva tu espacio')
@section('content')
<section class="hero"><div class="container hero-grid">
<div class="hero-copy"><span class="hero-badge"><x-icon name="car"/> RESERVA TU ESTACIONAMIENTO</span><h1>Tu espacio.<br><span class="hero-accent">Antes de llegar.</span></h1><p>Elige tu espacio y paga desde aquí. Cuando aprobemos el pago, tendrás 15 minutos para llegar.</p><div class="hero-actions"><a class="btn btn-primary btn-lg" href="{{ route('public.disponibilidad') }}">Reservar un espacio <x-icon name="arrow"/></a><a class="hero-secondary" href="{{ route('public.tarifas') }}">Ver tarifas</a></div><p class="hero-footnote">Pago por Yape o Plin · Confirmación tras revisar tu pago</p></div>
<aside class="hero-panel"><span class="eyebrow availability-heading"><x-icon name="chart"/> DISPONIBILIDAD ACTUAL</span><div class="availability-number">{{ $espaciosLibres }}<span>espacios disponibles de {{ $totalEspacios }}</span></div>
<label class="occupancy-label" for="occupancy-meter">{{ $espaciosLibres }} de {{ $totalEspacios }} espacios disponibles</label><progress id="occupancy-meter" class="occupancy-meter" max="{{ max(1,$totalEspacios) }}" value="{{ $espaciosLibres }}">{{ $espaciosLibres }} de {{ $totalEspacios }}</progress>
<div class="availability-breakdown"><div><strong>{{ $espaciosOcupados }}</strong><span><i class="status-dot occupied"></i>Ocupados</span></div><div><strong>{{ $espaciosReservados }}</strong><span><i class="status-dot reserved"></i>Reservados</span></div><div><strong>{{ $espaciosLibres }}</strong><span><i class="status-dot available"></i>Disponibles</span></div></div>@if($espaciosMantenimiento > 0)<p class="availability-maintenance">{{ $espaciosMantenimiento }} espacios no disponibles</p>@endif<p class="availability-hours"><x-icon name="clock"/> Lunes a domingo · 6:30 a. m. – 11:00 p. m.</p><a href="{{ route('public.disponibilidad') }}" class="btn btn-primary availability-cta">Elegir mi espacio <x-icon name="arrow"/></a><p class="availability-note">Estado al abrir la página. El plano muestra las actualizaciones.</p></aside>
</div></section>
<section class="section"><div class="container"><div class="flex-between flex-wrap mb-3"><div><span class="eyebrow"><x-icon name="map"/> ELIGE TU LUGAR</span><h2 class="section-title">Una llegada más sencilla</h2><p class="section-subtitle">Consulta el plano y elige un espacio libre para tu vehículo.</p></div><a class="btn btn-secondary" href="{{ route('public.disponibilidad') }}"><x-icon name="map"/> Explorar el plano 2D</a></div><div class="space-grid">@forelse($espacios->where('estado_actual','libre')->take(4) as $espacio)@include('public.space-card')@empty<div class="card"><h3>Por ahora no hay espacios libres</h3><p>Revisa el plano para consultar la disponibilidad más reciente.</p></div>@endforelse</div></div></section>
<section class="section-sm"><div class="container"><div class="public-price-callout"><div><span class="eyebrow"><x-icon name="wallet"/> SIN SORPRESAS AL RESERVAR</span><h2>Conoce el precio antes de pagar</h2><p>Consulta las tarifas por vehículo y horario. Verás el total al revisar tu reserva.</p></div><a class="btn btn-primary" href="{{ route('public.tarifas') }}">Consultar tarifas <x-icon name="arrow"/></a></div></div></section>
<section class="section"><div class="container"><span class="eyebrow">DE AQUÍ A TU ESPACIO</span><h2 class="section-title">Así de fácil</h2><div class="how-grid">@foreach(['Revisa espacios'=>'Consulta la disponibilidad en el plano.','Elige tu lugar'=>'Selecciona un espacio para tu vehículo.','Completa tu reserva'=>'Indica tu placa y cuánto tiempo te quedarás.','Envía tu pago'=>'Paga por Yape o Plin. Revisaremos tu operación o captura.','Llega y estaciona'=>'Consulta la aprobación en Mis reservas. Tendrás 15 minutos para llegar.'] as $title=>$description)<article><span class="how-number">0{{ $loop->iteration }}</span><h3>{{ $title }}</h3><p>{{ $description }}</p></article>@endforeach</div></div></section>
@endsection
