@extends('layouts.public')
@section('title', 'Parke’o · Reserva tu espacio')
@section('content')
<section class="hero"><div class="container hero-grid">
<div class="hero-copy"><span class="hero-badge"><x-icon name="car"/> RESERVA TU ESTACIONAMIENTO</span><h1>Tu espacio.<br><span class="hero-accent">Antes de llegar.</span></h1><p>Elige un espacio, registra tu placa y envía tu pago. Cuando el personal lo apruebe, tendrás 15 minutos para llegar.</p><div class="hero-actions"><a class="btn btn-primary btn-lg" href="{{ route('public.disponibilidad') }}">Reservar un espacio <x-icon name="arrow"/></a></div><p class="hero-footnote">Pago por Yape o Plin · Confirmación tras revisar tu pago</p><img class="hero-vehicle" src="/images/parkeo-car.svg" width="760" height="280" alt="" aria-hidden="true"></div>
<aside class="hero-panel"><span class="eyebrow availability-heading"><x-icon name="chart"/> DISPONIBILIDAD ACTUAL</span><div class="availability-number"><span data-availability-count="{{ $espaciosLibres }}" aria-hidden="true">{{ $espaciosLibres }}</span><span>espacios disponibles de {{ $totalEspacios }}</span></div>
<label class="occupancy-label" for="occupancy-meter">{{ $espaciosLibres }} de {{ $totalEspacios }} espacios disponibles</label><progress id="occupancy-meter" class="occupancy-meter" max="{{ max(1,$totalEspacios) }}" value="{{ $espaciosLibres }}">{{ $espaciosLibres }} de {{ $totalEspacios }}</progress>
<div class="availability-breakdown"><div><strong>{{ $espaciosOcupados }}</strong><span><i class="status-dot occupied"></i>Ocupados</span></div><div><strong>{{ $espaciosReservados }}</strong><span><i class="status-dot reserved"></i>Reservados</span></div><div><strong>{{ $espaciosLibres }}</strong><span><i class="status-dot available"></i>Disponibles</span></div></div>@if($espaciosMantenimiento > 0)<p class="availability-maintenance">{{ $espaciosMantenimiento }} espacios no disponibles</p>@endif<p class="availability-hours"><x-icon name="clock"/> Lunes a domingo · 6:30 a. m. – 11:00 p. m.</p><a href="{{ route('public.disponibilidad') }}" class="btn btn-primary availability-cta">Elegir mi espacio <x-icon name="arrow"/></a><p class="availability-note">Estado al abrir la página. El plano muestra las actualizaciones.</p></aside>
</div></section>
<section class="section"><div class="container"><span class="eyebrow">DE AQUÍ A TU ESPACIO</span><h2 class="section-title">Así de fácil</h2><div class="how-grid">@foreach(['Revisa espacios'=>'Consulta la disponibilidad en el plano.','Elige tu lugar'=>'Selecciona un espacio para tu vehículo.','Completa tu reserva'=>'Indica tu placa y cuánto tiempo te quedarás.','Envía tu pago'=>'Paga por Yape o Plin. Revisaremos tu operación o captura.','Llega y estaciona'=>'Consulta la aprobación en Mis reservas. Tendrás 15 minutos para llegar.'] as $title=>$description)<article><span class="how-number">0{{ $loop->iteration }}</span><h3>{{ $title }}</h3><p>{{ $description }}</p></article>@endforeach</div></div></section>
@endsection

@push('scripts')
@vite('resources/js/home-motion.js')
@endpush
