@extends('layouts.admin')
@section('page-title','Entradas y salidas')
@section('page-subtitle','Encuentra un vehículo, consulta su tiempo y registra el cobro.')
@section('content')
@include('admin.estadias.messages')
<div class="operation-links"><a class="btn btn-primary" href="{{ route('admin.estadias.create') }}">+ Registrar entrada</a><a class="btn btn-secondary" href="#buscar">Cobrar salida / buscar vehículo</a><a class="btn btn-secondary" href="{{ route('admin.placas.index') }}">Leer placa</a><a class="btn btn-secondary" href="{{ route('admin.monitoreo.index') }}">Espacios</a></div>
<div class="metrics-grid"><div class="metric primary"><span class="metric-label">Vehículos dentro</span><strong class="metric-value">{{ $activas }}</strong></div><div class="metric"><span class="metric-label">Esperando sensor</span><strong class="metric-value">{{ $esperando }}</strong></div><div class="metric"><span class="metric-label">Salidas de hoy</span><strong class="metric-value">{{ $salidasHoy }}</strong></div></div>
<section class="card"><div class="panel-heading"><h2>{{ request('estado') === 'historial' ? 'Historial de entradas y salidas' : 'Vehículos actualmente dentro' }}</h2></div>
<form class="filters" method="get"><div class="form-group"><label for="buscar">Placa, cliente o ticket</label><input id="buscar" name="buscar" value="{{ request('buscar') }}" placeholder="Ej. ABC123"></div><div class="form-group"><label for="estado">Mostrar</label><select id="estado" name="estado"><option value="activas">Dentro del estacionamiento</option><option value="historial" @selected(request('estado')==='historial')>Todo el historial</option></select></div><div class="form-group"><label for="fecha">Fecha de ingreso</label><input type="date" id="fecha" name="fecha" value="{{ request('fecha') }}"></div><button class="btn btn-secondary">Buscar</button></form>
<div class="table-responsive"><table class="data-table"><thead><tr><th>Vehículo / ticket</th><th>Espacio</th><th>Ingreso</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($estadias as $e)<tr><td><strong>{{ $e->placa }}</strong><small class="text-muted">{{ $e->codigo_ticket }}</small></td><td>{{ $e->espacio->codigo }}</td><td>{{ $e->hora_ingreso->format('d/m/Y H:i') }}<small class="text-muted">{{ (int) $e->hora_ingreso->diffInMinutes($e->hora_salida ?? now()) }} min desde el ingreso</small></td><td><span class="badge">{{ $e->estado_label }}</span></td><td><a class="btn btn-secondary" href="{{ route('admin.estadias.show',$e) }}">{{ $e->hora_salida?'Ver constancia':'Cobrar y registrar salida' }}</a></td></tr>@empty<tr><td colspan="5" class="empty-compact">No hay tickets para estos filtros.</td></tr>@endforelse</tbody></table></div>{{ $estadias->links() }}</section>
@endsection
