@extends('layouts.admin')
@section('page-title','Detalle del ticket')
@section('page-subtitle','Comprueba la estadía y confirma el pago antes de registrar la salida.')
@section('content')
@include('admin.estadias.messages')
<div class="entry-grid"><section class="card"><div class="panel-heading"><span class="badge">{{ $estadia->estado_label }}</span><a href="{{ route('admin.estadias.index') }}">Todos los tickets</a></div><div class="plate-display">{{ $estadia->placa }}</div><p>{{ $estadia->codigo_ticket }}</p><dl class="ticket-details"><div><dt>Espacio</dt><dd>{{ $estadia->espacio->codigo }}</dd></div><div><dt>Vehículo</dt><dd>{{ $estadia->vehiculoTipo->nombre }}</dd></div><div><dt>Ingreso</dt><dd>{{ $estadia->hora_ingreso->format('d/m/Y H:i:s') }}</dd></div><div><dt>Inicio del cobro</dt><dd>{{ $estadia->inicio_cobro?->format('d/m/Y H:i:s') ?? 'Esperando detección del sensor' }}</dd></div><div><dt>Origen del inicio</dt><dd>{{ ['sensor'=>'Sensor','manual'=>'Ticket de ingreso','manual_contingencia'=>'Contingencia manual'][$estadia->fuente_inicio] ?? $estadia->fuente_inicio }}</dd></div><div><dt>Tarifa al ingresar</dt><dd>{{ $estadia->tarifa_snapshot['nombre'] ?? 'Tarifa registrada' }}</dd></div>@if($estadia->reserva)<div class="wide"><dt>Reserva vinculada</dt><dd>{{ $estadia->reserva->codigo_reserva }} · {{ $estadia->minutos_contratados }} minutos contratados</dd></div>@endif
@if($estadia->motivo_inicio_manual)<div class="wide"><dt>Motivo de contingencia</dt><dd>{{ $estadia->motivo_inicio_manual }}</dd></div>@endif</dl><a class="btn btn-secondary" href="{{ route('admin.estadias.ticket',$estadia) }}" target="_blank" rel="noopener"><x-icon name="print"/>{{ $estadia->hora_salida?'Imprimir constancia':'Imprimir ticket' }}</a></section>
<section class="card">@if($estadia->hora_salida)<div class="settled-note"><x-icon name="check"/><h2>Salida registrada</h2></div><p>{{ $estadia->hora_salida->format('d/m/Y H:i:s') }}</p><div class="checkout-total"><small>Total de la estadía</small><strong>S/ {{ number_format($estadia->monto_total,2) }}</strong></div><dl class="checkout-breakdown"><dt>Adelanto</dt><dd>S/ {{ number_format($estadia->monto_adelantado,2) }}</dd><dt>Cobrado al salir</dt><dd>S/ {{ number_format($estadia->saldo_cobrado,2) }}</dd><dt>Medio de pago</dt><dd>{{ ucfirst($estadia->pagoSalida?->metodo_pago ?? 'Cubierto por adelanto') }}</dd>@if($estadia->vuelto!==null)<dt>Vuelto</dt><dd>S/ {{ number_format($estadia->vuelto,2) }}</dd>@endif</dl>
@elseif(!$estadia->inicio_cobro)<h2>Esperando al sensor</h2><p>El tiempo empezará cuando el sensor detecte el vehículo estacionado. Actualiza esta página después de la lectura.</p><a class="btn btn-secondary" href="{{ route('admin.estadias.show',$estadia) }}">Consultar lectura</a><hr><details><summary>Registrar inicio por contingencia</summary><p>Usa esta opción si verificaste personalmente que el vehículo está estacionado y el sensor no responde.</p><form method="post" action="{{ route('admin.estadias.inicio-manual',$estadia) }}">@csrf<div class="form-group"><label for="inicio_cobro">Hora observada de estacionamiento</label><input type="datetime-local" id="inicio_cobro" name="inicio_cobro" required value="{{ old('inicio_cobro',now()->format('Y-m-d\TH:i')) }}"></div><div class="form-group"><label for="motivo">Motivo de la intervención</label><textarea id="motivo" name="motivo" minlength="10" maxlength="1000" required>{{ old('motivo') }}</textarea></div><button class="btn btn-primary">Confirmar inicio manual</button></form></details>
@else<h2>Cobro de salida</h2><p>{{ $liquidacion['minutos'] }} minutos de estadía · corte {{ $liquidacion['hasta']->format('H:i:s') }}</p><div class="checkout-total"><small>Saldo a cobrar</small><strong>S/ {{ number_format($liquidacion['saldo_centavos']/100,2) }}</strong></div><dl class="checkout-breakdown"><dt>Total</dt><dd>S/ {{ number_format($liquidacion['total_centavos']/100,2) }}</dd><dt>Pagado por adelantado</dt><dd>S/ {{ number_format($liquidacion['adelanto_centavos']/100,2) }}</dd></dl><p class="text-muted">{{ $liquidacion['detalle'] }}</p><p class="text-muted">Importe válido por 5 minutos. <a href="{{ route('admin.estadias.show',$estadia) }}">Actualizar cálculo</a></p><form method="post" action="{{ route('admin.estadias.salida',$estadia) }}">@csrf<input type="hidden" name="cotizacion" value="{{ $cotizacion }}">@if($liquidacion['saldo_centavos']>0)<div class="form-group"><label for="metodo_pago">Medio de pago</label><select id="metodo_pago" name="metodo_pago" data-payment-method><option value="efectivo" @selected(old('metodo_pago')==='efectivo')>Efectivo</option><option value="yape" @selected(old('metodo_pago')==='yape')>Yape</option><option value="plin" @selected(old('metodo_pago')==='plin')>Plin</option></select></div><div class="form-group" data-cash-field><label for="efectivo_recibido">Efectivo recibido (S/)</label><input id="efectivo_recibido" name="efectivo_recibido" type="number" min="0" step="0.01" value="{{ old('efectivo_recibido') }}"></div><div class="form-group" data-transfer-field><label for="referencia_pago">Número de operación</label><input id="referencia_pago" name="referencia_pago" value="{{ old('referencia_pago') }}" maxlength="80"><small>Verifica el abono en el celular del negocio.</small></div><label class="checkbox-row"><input type="checkbox" name="pago_verificado" value="1" required> Confirmo que recibí y verifiqué el pago.</label>@else<div class="alert alert-success">El adelanto cubre la estadía. No hay un cobro adicional.</div>@endif<button class="btn btn-primary"><x-icon name="exit"/>Confirmar salida</button></form>@endif</section></div>
@endsection
